### ISSUE TITLE
New NDT_CONNECTED drawtype for fences, etc.

### ISSUE THREAD

**Issue by lnjX** [Gamerbude/Minetest_TNG#14]
They in minetest_game already using it the NDT_CONNECTED drawtype.
In this drawtype the client connects fences or whatever not the server, so it's _faster_!
But they are only working for the new dev-clients (and servers), I already added walls that use this drawtype, but they are disabled by default. (You have to turn it on in the advanced settings, Enable Minetest-Dev Content)

I would like to update the fences too, so I think we should release a v16.04-1 (for MT 0.4.13), update the fences and release the v16.04-2 (for MT 0.4.14).

What do you think?? :thought_balloon:

**Comment by jbruechert** [comment]
ok, a minetest-dev release would be good, but I think 0.4.14 may be released in this week, so we maybe don't need it. But in future we probably want to use dev-engine features so a release for minetest-dev would be welcome to me.

**Comment by lnjX** [comment]
Definitely I will release a v16.04 for Minetest 0.4.13, because there are many new features that are working there too. And on servers many people use the 0.4.12, because you have got a better performance there. The current release is compatible with that, but the new features are not, so 
we could create a branch for compatibility with outdated versions (Client 0.4.12 and Server 0.4.13). And those who want the new features can use the master branch and people who want to have dev-only features can use the 'experimental' branch.

But maybe that is too much.

stable-server (for Client 0.4.12, Server 0.4.13), master (for Client/Server current stable), experimental (for current dev)

**Comment by lnjX** [comment]
I closed this because I think the conversation has finished.
