### ISSUE TITLE
[Bug] Spawners not registered in peaceful mode

### ISSUE THREAD

**Issue by ghost** [Gamerbude/Minetest_TNG#32]
I'm getting a lot of errors like:
`ERROR[Server]: Map::setNode(): Not allowing to place CONTENT_IGNORE while trying to replace "air" at (418,-19,976) (block (26,-2,61))`

They seem to occur when I've moved into a new area and terrain is being generated. I've gone to the coordinates in the errors several times and they are always in the center of a room in a dungeon made of sandstone brick. 

I'm using sfan5's 64bit build [https://forum.minetest.net/viewtopic.php?f=42&t=1523&start=525#p229282](url)
Here's the debug log: [err.txt](https://github.com/minetest-games/Minetest_TNG/files/453477/err.txt)
Screen shot standing where an error occured: [http://n72i.imgup.net/screenshotae35.png](url)

**Comment by lnjX** [comment]
strange..
Are these coordinates into a wall (or where a wall should be) or are they over the ground (like a spawner from CME)?
Maybe this an engine-side bug? (dungeon generation is engine-side)

**Comment by ghost** [comment]
I may have spoken too soon. I'm not getting the error with Krock's build from today so it was probably an engine error.

**Comment by lnjX** [comment]
Ah ok, so this issue is solved? I'll close it. If you get this bug again you can reopen it. :smiley:

**Comment by ghost** [comment]
The coordinates were in the air. The spawner from CME may have triggered the error, but it works now.

**Comment by ghost** [comment]
The problem has returned. It's seems to be related to the zombie spawner as I only get the errors if I have set only_peaceful_mobs = true. Using the seed 17607220401755498669 and mapgen v7 I will get the errors shortly after I spawn if I set only_peaceful_mobs = true but no errors if I leave it at the default.

**Comment by lnjX** [comment]
@zing269 Arhh I think I've got the bug ... the spawners are ONLY registered when the game is not in peaceful mode. So when the spawners are generated (in peaceful) it returns an error message because the spawner is not defined.

**Comment by ghost** [comment]
Perhaps you can move the check for peaceful in to the code that decides whether to spawn or not. That way the spawners will be created but not do anything unless one turned hostile mobs back on.

**Comment by lnjX** [comment]
@zing269 I'm nearly done with it, will be merged tomorrow. :smiley:
