### ISSUE TITLE
I'm backporting. What is the license?

### ISSUE THREAD

**Issue by mieu12** [Gamerbude/Minetest_TNG#37]

**Comment by jbruechert** [comment]
https://github.com/lnjX/Minetest_TNG/blob/master/LICENSE.txt

**Comment by lnjX** [comment]
Btw, where are you backporting to? minetest_game? If you ping me under your pull-requests, I can grant you permission to use the code under LGPL-2.1-or-later. If you need another license, please say so :)

**Comment by mieu12** [comment]
Thank you. :)

**Comment by mieu12** [comment]
Ok, I'm backporting to github.com/mieu12/Minetest_TNG-1

**Comment by lnjX** [comment]
@mieu12 Do you want to continue to develop Minetest TNG / build upon it? That's no backporting and you can do that under the GPLv3+ without asking me (or anybode else).

Backporting would essentially mean copying code from this fork back to the original minetest_game (or to another new fork of minetest_game).

**Comment by mieu12** [comment]
Ok, sorry. I will add somethings from the [ToDo] list.

**Comment by mieu12** [comment]
I thought it was already on LGPL-2.1.

**Comment by lnjX** [comment]
@mieu12 It's GPL-3.0-or-later, parts of the project may have other GPL-3.0-compatible licenses though.
