### ISSUE TITLE
Add new papyrus block (a bundle)

### ISSUE THREAD

**Issue by lnjX** [Gamerbude/Minetest_TNG#6]
**JBBgameich:**

> What about this Papyrus Block textures?
> ![default_bamboo_light](https://cloud.githubusercontent.com/assets/13609393/13676221/3f2dbcfa-e6e5-11e5-91fd-1985cbee5e99.png)
> ![default_bamboo](https://cloud.githubusercontent.com/assets/13609393/13676222/3f36ddbc-e6e5-11e5-9610-27a0cd13fd0a.png)
> ![default_bamboo_superlight](https://cloud.githubusercontent.com/assets/13609393/13676317/98cfd554-e6e5-11e5-8936-7ae936ca6db4.png)

**LNJplus:**

> I think the textures should be green and don't forget we need a top texture too. (And its not bamboo its papyrus!)
> 
> And thats only the issue for discussing about what we need and what we dont need, so please create a new issue. (I can remove your posts, if I want)
> 
> So ich schreib jetzt einfach so auf Deutsch (sollte aber nicht standard werden)
> Wenn man einen gelben Block braucht kann man straw nehmen deswegen finde ich es unnoetig noch einen gelben hinzuzufuegen. Ausserdem muessten dann die normalen papyri auch gelb sein

**JBBgameich:**

> Inside the trunks Papyrus is not green I think....
> Bamboo is green outside too and inside lightbrown. 
> ![images](https://cloud.githubusercontent.com/assets/13609393/13676791/85e6630c-e6e7-11e5-8056-033757fdf5af.jpg)
> ![bamboo](https://cloud.githubusercontent.com/assets/13609393/13676793/89c3e5ee-e6e7-11e5-8aa0-3d67cbee02ad.jpg)
> 
> And I think the trunks of Bamboo and Papyrus are very simular.
> But here is a green variation of the texture:
> ![default_papyrus_block_green](https://cloud.githubusercontent.com/assets/13609393/13676972/5d3dd006-e6e8-11e5-95cc-fc6e0925d830.png)

**LNJplus:**

> But you cann't see how it looks inside! It's normal papyrus but just bundled in size of a block!
> 
> You don't have to do this texture, if you don't want. It's my idea to add this and I want that the block is green. :wink: 

**JBBgameich:**

> Ah, you mean a bundle! In your description you don’t said that.

**LNJplus:**

> I thought that it would be obviously that you don't cut open the papyrus.

**Comment by jbruechert** [comment]
what about this:
![default_papyrus_block_top](https://cloud.githubusercontent.com/assets/13609393/13678098/448ca1d6-e6ed-11e5-8f6a-729a97bb9fbe.png)

![default_papyrus_block](https://cloud.githubusercontent.com/assets/13609393/13677865/39bfa088-e6ec-11e5-99d1-9ac5824faabc.png)

**Comment by lnjX** [comment]
Nice textures :+1:, but I would change some small things:
- Strings / Papyri "Leaves" (darker than the other coulors) that holds the papyri together
- the top texture don't really looks so perfect maybe try to make single trunks (only one pixel in the middle should be bright brown)

**Comment by lnjX** [comment]
I think I can go and write the code. Or do you want to do that?? - should be default

**Comment by lnjX** [comment]
Merged: https://github.com/gamerbude/Minetest_TNG/commit/6cbf16ea65d6007ec87e53775df3aa81dade5c9d
